// Courses Studio — P4 course portability: zip bundle engine (export/import).
//
// On-disk layout produced by ingest (see electron/courses/ingest.ts):
//   <coursesRoot>/<courseId>/lessons/<slug>.md
//   <coursesRoot>/<courseId>/assets/**          (media, referenced as course-media://<id>/<rel>)
// runCourseImport composes lesson row ids as `${courseId}:${slugs[index]}` and persistLesson
// writes `path.join(lessonsDir, \`${slug}.md\`)`, so the file stem is exactly the substring of
// the id after the LAST ':' (ingest's slugs are kebab-case and never contain ':').
//
// A bundle zip contains:
//   meta.json     — CourseBundleMeta catalog at the zip root (schemaVersion 1)
//   lessons/*.md  — one per lesson row, path `lessons/<slugOfLesson(id)>.md`
//   assets/**     — full asset tree with relative paths preserved
//
// Pure node:fs/promises + node:path file-level functions; NO 'electron' imports so tests run
// under ELECTRON_RUN_AS_NODE. No value is ever imported from courseStore at runtime (this module
// stays DB-free); every failure surfaces as { ok:false, error } — nothing throws across the API.

import JSZip from "jszip";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { resolveCourseDataDir, safeCourseDirName } from "./courseDir";

export const BUNDLE_SCHEMA_VERSION = 1;

/** Catalog + lesson rows persisted as meta.json at the zip root (schemaVersion 1). */
export interface CourseBundleMeta {
  schemaVersion: number;
  courseId: string;
  name: string;
  profile?: string | null;
  sourceUrl: string;
  status: string;
  enabled: boolean | number;
  lessons: Array<{
    id: string;
    title: string;
    url: string;
    kind?: string | null;
    parent?: string | null;
    orderNo: number;
    tocPath?: string | null;
    completedAt?: string | null;
  }>;
  exportedAt: string;
  fileCount?: number;
}

/**
 * Success carries the generated bytes in addition to their size so callers can hand the artifact
 * off (save dialog / IPC) without this module inventing a disk location.
 */
export type ExportBundleResult =
  | { ok: true; size: number; zip: Buffer }
  | { ok: false; error: string };

export type ImportBundleResult =
  | { ok: true; courseId: string; meta: CourseBundleMeta }
  | { ok: false; error: string };

type BundleLessonRow = CourseBundleMeta["lessons"][number];

/** Instance shape of the jszip default import (the package types its class via `export =`). */
type JsZipInstance = InstanceType<typeof JSZip>;

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function fail(err: unknown, what: string): { ok: false; error: string } {
  return { ok: false, error: `${what}: ${errorMessage(err)}` };
}

/**
 * On-disk file stem for a lesson row id. Mirrors ingest's pairing of `id = \`${courseId}:${slug}\``
 * with the write site `` path.join(lessonsDir, `${slug}.md`) `` — hence "substring after the last
 * ':'" (the whole id when it has no ':'). Reused by export and rekeyLessons so ids/files line up.
 */
export function slugOfLesson(id: string): string {
  const idx = id.lastIndexOf(":");
  return idx === -1 ? id : id.substring(idx + 1);
}

/** Coerce one meta.json lesson row to the canonical shape; returns an error string when corrupt. */
function normalizeLessonRow(raw: unknown, index: number): BundleLessonRow | string {
  const r = (typeof raw === "object" && raw !== null ? raw : {}) as Record<string, unknown>;
  const id = typeof r.id === "string" ? r.id.trim() : "";
  const url = typeof r.url === "string" ? r.url.trim() : "";
  if (id.length === 0 || url.length === 0) {
    return `bundle meta.json lesson[${index}] is missing id or url`;
  }
  const orderNo = Number(r.orderNo);
  if (!Number.isFinite(orderNo)) {
    return `bundle meta.json lesson[${index}] has a non-numeric orderNo`;
  }
  const strOrNull = (v: unknown): string | null =>
    typeof v === "string" && v.length > 0 ? v : null;
  const title = typeof r.title === "string" && r.title.trim().length > 0 ? r.title : id;
  return {
    id,
    title,
    url,
    kind: strOrNull(r.kind),
    parent: strOrNull(r.parent),
    orderNo,
    tocPath: strOrNull(r.tocPath),
    completedAt: strOrNull(r.completedAt),
  };
}

/** Validate + normalize a parsed meta.json; returns an error string (distinct per failure mode). */
function validateBundleMeta(raw: unknown): CourseBundleMeta | string {
  const m = (typeof raw === "object" && raw !== null ? raw : {}) as Record<string, unknown>;

  const schemaVersion = typeof m.schemaVersion === "number" ? m.schemaVersion : NaN;
  if (schemaVersion !== BUNDLE_SCHEMA_VERSION) {
    return typeof m.schemaVersion === "undefined"
      ? "bundle meta.json has no schemaVersion"
      : `unsupported bundle schemaVersion ${String(m.schemaVersion)} (expected ${BUNDLE_SCHEMA_VERSION})`;
  }

  const courseId = typeof m.courseId === "string" ? m.courseId.trim() : "";
  if (courseId.length === 0) return "bundle meta.json is missing courseId";
  const sourceUrl = typeof m.sourceUrl === "string" ? m.sourceUrl.trim() : "";
  if (sourceUrl.length === 0) return "bundle meta.json is missing sourceUrl";

  const lessonsRaw = Array.isArray(m.lessons) ? m.lessons : null;
  if (lessonsRaw === null || lessonsRaw.length === 0) {
    return "bundle contains no lessons";
  }

  const lessons: BundleLessonRow[] = [];
  for (let i = 0; i < lessonsRaw.length; i += 1) {
    const row = normalizeLessonRow(lessonsRaw[i], i);
    if (typeof row === "string") return row;
    lessons.push(row);
  }

  // localMdPath is deliberately dropped here: paths are machine-specific and the importer sets a
  // fresh one from disk after extraction.
  const name = typeof m.name === "string" && m.name.trim().length > 0 ? m.name : courseId;
  const status = typeof m.status === "string" && m.status.length > 0 ? m.status : "ready";
  const profile = typeof m.profile === "string" ? m.profile : null;
  const enabled: boolean | number =
    typeof m.enabled === "boolean" || typeof m.enabled === "number" ? m.enabled : true;
  const exportedAt =
    typeof m.exportedAt === "string" && m.exportedAt.length > 0
      ? m.exportedAt
      : new Date().toISOString();

  return { schemaVersion: BUNDLE_SCHEMA_VERSION, courseId, name, profile, sourceUrl, status, enabled, lessons, exportedAt };
}

/** Recursively add every file under rootDir at `assets/<rel>`, preserving subdirectories. */
async function addAssetTree(zip: JsZipInstance, rootDir: string, currentDir: string): Promise<void> {
  let entries;
  try {
    entries = await readdir(currentDir, { withFileTypes: true });
  } catch {
    return; // missing assets dir (at any depth) simply yields no further entries.
  }
  for (const entry of entries) {
    const full = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      await addAssetTree(zip, rootDir, full);
    } else if (entry.isFile()) {
      // Zip paths are forward-slash even on Windows.
      const rel = path.relative(rootDir, full).split(path.sep).join("/");
      zip.file(`assets/${rel}`, await readFile(full));
    }
  }
}

/**
 * Pack the on-disk course into an in-memory bundle: one `lessons/<slug>.md` per lesson row whose
 * file exists, the whole `assets/` tree (relative paths preserved), and meta.json at the root.
 */
export async function exportCourseBundle(
  coursesRoot: string,
  courseId: string,
  meta: CourseBundleMeta,
): Promise<ExportBundleResult> {
  try {
    const zip = new JSZip();
    // On-disk dirs use the sanitized id (courseDir.ts); legacy raw-id dirs still resolve.
    const courseDir = resolveCourseDataDir(coursesRoot, courseId);
    const lessonsDir = path.join(courseDir, "lessons");
    for (const lesson of Array.isArray(meta.lessons) ? meta.lessons : []) {
      // Rows without an on-disk file (partial import, deleted md) are skipped, not fatal.
      let data: Buffer;
      try {
        data = await readFile(path.join(lessonsDir, `${slugOfLesson(lesson.id)}.md`));
      } catch {
        continue;
      }
      zip.file(`lessons/${slugOfLesson(lesson.id)}.md`, data);
    }

    const assetsDir = path.join(courseDir, "assets");
    await addAssetTree(zip, assetsDir, assetsDir); // no-op when the directory does not exist.

    zip.file("meta.json", JSON.stringify(meta, null, 2));

    const buffer = await zip.generateAsync({ type: "nodebuffer" });
    return { ok: true, size: buffer.length, zip: buffer };
  } catch (err) {
    return fail(err, "exportCourseBundle");
  }
}

/** True when a raw (pre-sanitization) zip entry name tries to reach outside its parent tree. */
function looksLikeEscape(rawName: string): boolean {
  const normalized = rawName.replace(/\\/g, "/");
  if (normalized.startsWith("/") || /^[a-zA-Z]:/.test(normalized)) return true; // absolute paths.
  return normalized.split("/").some((part) => part === "..");
}

/** Spec'd zip-slip backstop: the resolved target must stay inside courseDir. */
function staysInside(courseDir: string, target: string): boolean {
  const root = path.resolve(courseDir);
  const resolved = path.resolve(target); // normalize() + absolutize in one step.
  return resolved === root || resolved.startsWith(root + path.sep);
}

/** A course id doubles as a directory name under coursesRoot; refuse anything that could climb out. */
function isSafeCourseDirName(id: string): boolean {
  if (typeof id !== "string" || id.length === 0) return false;
  if (id.includes("/") || id.includes("\\")) return false;
  const normalized = path.normalize(id);
  return normalized === id && normalized !== "." && !normalized.startsWith("..");
}

/**
 * Extract a bundle zip under `<coursesRoot>/<finalCourseId>/`. The caller resolves courseId
 * conflicts (and passes targetCourseId) BEFORE calling this. Only top-level `lessons/`, `assets/`
 * and `meta.json` are understood; any entry whose name would escape the course directory rejects
 * the whole import atomically (entries are classified before anything is written).
 */
export async function importCourseBundle(
  zipBytes: Buffer,
  targetCourseId: string | null,
  coursesRoot: string,
): Promise<ImportBundleResult> {
  let zip: JsZipInstance;
  try {
    zip = await JSZip.loadAsync(zipBytes);
  } catch (err) {
    return fail(err, "importCourseBundle: not a readable zip archive");
  }

  const metaEntry = zip.file("meta.json");
  if (!metaEntry || metaEntry.dir) {
    return { ok: false, error: "bundle is missing meta.json" };
  }

  let rawMeta: unknown;
  try {
    rawMeta = JSON.parse(await metaEntry.async("string"));
  } catch (err) {
    return fail(err, "importCourseBundle: bundle meta.json is not valid JSON");
  }

  const validated = validateBundleMeta(rawMeta);
  if (typeof validated === "string") return { ok: false, error: validated };
  const meta = validated;

  const finalCourseId = targetCourseId ?? meta.courseId;
  if (!isSafeCourseDirName(finalCourseId)) {
    return { ok: false, error: "importCourseBundle: refusing unsafe course directory name" };
  }

  // Classify every entry first (no writes yet) so a malicious bundle is rejected atomically.
  // Sanitized on-disk name; the isSafeCourseDirName guard above already rejected
  // traversal ids (dots are legal chars the sanitizer would not remove).
  const courseDir = path.join(coursesRoot, safeCourseDirName(finalCourseId));
  const pendingWrites: Array<{ name: string; target: string }> = [];
  let rejectReason: string | null = null;

  zip.forEach((name, fileObj) => {
    if (rejectReason !== null || fileObj.dir || name === "meta.json") return;

    // jszip quarantines entries whose raw names contained escapes and exposes the original here —
    // treat any of them as an attack rather than as an unknown path to skip.
    const original = fileObj.unsafeOriginalName;
    if (typeof original === "string" && looksLikeEscape(original)) {
      rejectReason = `unsafe bundle entry escapes course directory: ${original}`;
      return;
    }

    const parts = name.replace(/\\/g, "/").split("/"); // zip paths are forward-slash.
    if (parts.some((part) => part === "..")) {
      rejectReason = `unsafe bundle entry escapes course directory: ${name}`;
      return;
    }

    const top = parts[0];
    if ((top !== "lessons" && top !== "assets") || parts.length < 2) {
      return; // unknown path (stray files, other folders) — skipped by design.
    }

    const target = path.join(courseDir, top, ...parts.slice(1));
    if (!staysInside(courseDir, target)) {
      rejectReason = `unsafe bundle entry escapes course directory: ${name}`;
      return;
    }
    pendingWrites.push({ name, target });
  });

  if (rejectReason !== null) return { ok: false, error: rejectReason };

  for (const item of pendingWrites) {
    const entry = zip.file(item.name);
    if (!entry || entry.dir) continue; // cannot vanish in practice — stay safe regardless.
    try {
      await mkdir(path.dirname(item.target), { recursive: true });
      await writeFile(item.target, await entry.async("nodebuffer"));
    } catch (err) {
      return fail(err, "importCourseBundle: extraction failed");
    }
  }

  return { ok: true, courseId: finalCourseId, meta };
}

/**
 * Rewrite a bundle's lesson rows for `newCourseId`: ids become `<newCourseId>:<slug>` (same slug
 * derivation as ingest), every other field is copied as-is. localMdPath is dropped entirely — the
 * importer computes it fresh from the on-disk paths after extraction.
 */
export function rekeyLessons(
  meta: CourseBundleMeta,
  newCourseId: string,
): CourseBundleMeta["lessons"] {
  const rows = Array.isArray(meta?.lessons) ? meta.lessons : [];
  return rows.map((lesson) => ({
    id: `${newCourseId}:${slugOfLesson(lesson.id)}`,
    title: lesson.title,
    url: lesson.url,
    kind: lesson.kind ?? null,
    parent: lesson.parent ?? null,
    orderNo: lesson.orderNo,
    tocPath: lesson.tocPath ?? null,
    completedAt: lesson.completedAt ?? null,
  }));
}
